### ISSUE TITLE
Testing error

### ISSUE THREAD

**Issue by ashishgupta2598** [ljsabc/MangaLineExtraction#6] opened 2020-01-28 15:11 UTC
At the time of running the code I got this error. I have tensorflow==1.14.0 and keras ==1.2.0 and theno as 1.4.0 
```
Traceback (most recent call last):
  File "test_mse.py", line 85, in <module>
    test(sys.argv[1])
  File "test_mse.py", line 51, in test
    model = loadModel(home)
  File "test_mse.py", line 44, in loadModel
    model = model_from_json(loaded_model_json)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/models.py", line 210, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/utils/layer_utils.py", line 38, in layer_from_config
    return layer_class.from_config(config['config'], custom_objects=custom_objects)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/engine/topology.py", line 2575, in from_config
    process_layer(layer_data)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/engine/topology.py", line 2572, in process_layer
    layer(input_tensors)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/engine/topology.py", line 1450, in __call__
    node_indices, tensor_indices)
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/keras/engine/topology.py", line 1329, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 384, None, None), (None, 192, None, None)]
```

**Comment by ljsabc** [comment] 2020-01-28 15:12
Duplicate of #1 .

**Closed as completed by ljsabc** 2020-01-28 15:12 UTC
